version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: cimg/base:stable # You can adjust the Node.js version as needed
  working_directory: ~/app
  
  steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.12.1'
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Install Serve
          command: npm install -g serve
      - run:
          name: Serve React Application
          command: serve -s build

  run_selenium_tests:
    docker:
      - image: circleci/openjdk:8-jdk # Choose the appropriate Java version

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Clone Selenium UI Tests Repository
          command: git clone https://github.com/bbagishbek/expero selenium-tests
          
      - run:
          name: Run Selenium UI Tests
          command: |
            cd selenium-tests
            mvn install
            mvn test -DsuiteXmlFile=testng.xml

workflows:
  version: 2
  build-and-run-react:
    jobs:
      - build
      - run_selenium_tests:
          requires:
            - build
