version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14 # You can adjust the Node.js version as needed

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Build Application
          command: npm run build

  run_react_app:
    docker:
      - image: circleci/node:14 # Use a compatible Node.js version

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install Serve
          command: npm install -g serve

      - run:
          name: Serve React Application
          command: serve -s build

workflows:
  version: 2
  build-and-run-react:
    jobs:
      - build
      - run_react_app:
          requires:
            - build

